name: Build and Publish Docker Image

on:
  push:
    branches:
      - main

jobs:
  build_and_publish_backend:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Create .env file
      run: |
        echo "AWS_S3_BUCKET=${{ secrets.AWS_S3_BUCKET }}" > ./backend/streamingService/.env
        echo "AWS_REGION=${{ secrets.AWS_REGION }}" >> ./backend/streamingService/.env
        echo "AWS_KEY_ID=${{ secrets.AWS_KEY_ID }}" >> ./backend/streamingService/.env
        echo "AWS_SECRET_KEY=${{ secrets.AWS_SECRET_KEY }}" >> ./backend/streamingService/.env

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}


    - name: Build and push Docker image
      run: |
        docker buildx build --platform linux/amd64,linux/arm64/v8 --push --tag ${{ secrets.DOCKER_USERNAME }}/streaming-image:latest ./backend/streamingService